sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t ashevade/docker-react -f Dockerfile.dev .

script:
    docker run -e CI=true ashevade/docker-react npm run test 
deploy:
  provider: elasticbeakstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucket_name: "elasticbeanstalk-us-east-2-249515834673"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY

            